window.quotes = [
  {
    title: 'Epictetus - The Art of Living',
    quotes: [
      'Happiness and freedom begin with a clear understanding of one principle: Some things are within our control, and some things are not.',
      'Keep your attention focused entirely on what is truly your own concern, and be clear that what belongs to others is their business and none of yours.',
      'Circumstances do not rise to meet our expectations. Events happen as they do. People behave as they are. Embrace what you actually get',
      'Open your eyes: See things for what they really are, thereby sparing yourself the pain of false attachments and avoidable devastation',
      'When something happens, the only thing in your power is your attitude toward it; you can either accept it or resent it',
      `Events don't hurt us, but our views of them can`,
      'We cannot choose our external circumstances, but we can always choose how we respond to them.',
      'Never depend on the admiration of others. There is no strength in it. Personal merit cannot be derived from an external source. It is not to be found in your personal associations, not can it be found in the regard of other people.',
      `Other people's views and troubles can be contagious. Don't sabotage yourself by unwittingly adopting negative, unproductive attitudes through your associations with others`,
      `Do you wish to be invincible? Then don't enter into combat with what you have no real control over.`,
      'Stop aspiring to be anyone other than your own best self: for that does fall within your control.',
      'Try not to merely react in the moment. Pull back from the situation. Take a wider view; compose yourself.',
      'Spiritual progress is made through confronting death and calamity',
      'Instead of averting your eyes from the painful events of life, look at them squarely and contemplate them often. By facing the realities of death, infirmity, loss, and disappointment, you free yourself of illusions and false hopes and you avoid miserable, envious thoughts.',
      `In trying to please other people, we find ourselves misdirected toward what lies outside our sphere of influence. In doing so we lose our hold on our life's purpose.`,
      `Content yourself with being a lover of wisdom, a seeker of the truth. Return and return again to what is essential and worthy.`,
      'Character matters more than reputation',
      `It's better to be a good person and fulfill your obligations that to have renown and power.`,
      'Follow through on all your generous impulses. Do not question them, especially if a friend needs you; act on his or her behalf. Do not hesitate!',
      `Clearly define the person you want to be: Who exactly do you want to be? What kind of person do you want to be? What are your personal ideals? Whom do you admire? What are their special traits that you would make your own?`,
      `Most of what passes for legitimate entertainment is inferior or foolish and only caters to or exploits people's weaknesses. Avoid being one of the mob who indulges in such pastimes. Your life is too short and you have important things to do.`,
      'Give your best and always be kind.',
      'Quit the evasions. Stop giving yourself needless trouble',
      'Take care not to casually discuss matters that are of great importance to you with people who are not important to you. Your affairs will become drained of preciousness. ',
      'Practice having a grateful attitude and you will be happy.',
      'Stay the course, in good weather and bad',
      `Your relentless pursuit of wisdom postpones your actually possessing it. Quit chasing after tonics and new teachers. The latest fashionable sage or book or diet or belief doesn't move you in the direction of a flourishing life. You do. Renounce externals once and for all`,
      'Pursue the good ardently. But if your efforts fall short, accept the result and move on',
      'The virtuous life holds these as treasures: your own right action, your fidelity, honor, and decency.',
      'Why should we bother being good? To be good is to be happy; to be tranquil and worry-free. ',
      `Goodness isn't ostentatious piety or showy good manners. It's a lifelong series of subtle readjusting of our character. We fine-tune our thoughts, words, and deeds in a progressively wholesome direction. The virtue inheres in our intentions and our deeds, not in the results`,
      'Whenever someone does something foolish, pity him rather than yield to hatred and anger as so many do.',
      `The appropriate response to bad deeds is pity for the perpetrators, since they have adopted unsound beliefs and are deprived of the most valuable human capacity: the ability to differentiate between what's truly good and bad for them.`,
      'It is incumbent that your thoughts, words, and deeds match up.',
      'Forgive others for their misdeeds over and over again. This gesture fosters inner ease.',
      'Forgive yourself over and over and over again. Then try to do better next time.',
      `To live a life of virtue, you have to become consistent, even when it isn't conceivable, comfortable, or easy`,
      `Don't just say you have read books. Show that through them you have learned to think better, to be a more discriminating and reflective person. Books are the training weights of the mind.`,
      'Be a citizen of the world',
      'Be suspicious of convention. Take charge of your own thinking.',
      'If people treat you disrespectfully or speak unkindly about you, remember that they do so from their impression that it is right to do so.',
      `Those who are morally untrained spend an inordinate amount of time on their bodies. Carry out your animal functions incidentally. Your main attention should be given to the care and development of your reason. For through reason, you are able to understand nature's laws`,
      `Respect your body's needs. Give your body excellent care to promote its health and well-being.`,
      'Regularly ask yourself, "How are my thoughts, words, and deeds affecting my friends, my spouse, my neighbor, my child, my employer, my subordinates, my fellow citizens?"',
      'Speak only with good purpose',
      'Be honest with yourself. Clearly assess your strengths and weaknesses.',
      `In trying to please other people, we find ourselves misdirected toward what lies outside our sphere of influence. In doing so we lose our hold on our life's purpose`,
      `Many people who have progressively lowered their personal standards in an attempt to win social acceptance and life's comforts bitterly resent those of philosophical bent who refuse to compromise their spiritual ideals and seek to better themselves.`,
      'If you encounter an attractive person, then self-restraint is the resource needed; if pain or weakness, then stamina; if verbal abuse, then patience',
      'Your will is always within your power',
      'Nothing truly stops you. Nothing truly holds you back. For your own will is aways your control.',
      'There is a time and place for diversion and amusements, but you should never allow them to override your true purposes.',
      'Open your eyes: See things for what they really are, thereby sparing yourself the pain of false attachments and avoidable devastation.',
      `Don't declare yourself to be a wise person or discuss your spiritual aspirations with people who won't appreciate them. Show your character and your commitment to personal nobility through your actions.`,
      'Through vigilance, we can forestall the tendency to excess. Your possessions should be proportionate to the needs of your body, just as the shoe should fit the foot',
    ]
  },
  {
    title: 'Naval Ravikant',
    quotes: [
      `Don’t take yourself so seriously. You’re just a monkey with a plan.`,
      `Happiness is what’s there when you remove the sense that something is missing in your life.`,
      'We crave experiences that will make us be present, but the cravings themselves take us from the present moment.',
      'Anticipation for our vices pulls us into the future. Eliminating vices makes it easier to be present.',
      'Desire is a contract you make with yourself to be unhappy until you get what you want.',
      'Happiness is being satisfied with what you have. Success comes from dissatisfaction. Choose.',
      'The enemy of peace of mind is expectations drilled into you by society and other people.',
      'When working, surround yourself with people more successful than you. When playing, surround yourself with people happier than you.',
      `If you can't see yourself working with someone for life, don’t work with them for a day.`,
      'To make an original contribution, you have to be irrationally obsessed with something.',
      'Meditation is intermittent fasting for the mind.',
      'Life-hack: When in bed, meditate. Either you will have a deep meditation or fall asleep. Victory either way.',
      `Insight meditation lets you run your brain in debug mode until you realize you're just a subroutine in a larger program.`,
      `The hardest thing is not doing what you want —it's knowing what you want.`,
      'Everyone starts out innocent. Everyone is corrupted. Wisdom is the discarding of vices and the return to virtue, by way of knowledge.',
      'Inspiration is perishable—act on it immediately.',
      'Read enough, and you become a connoisseur. Then you naturally gravitate more toward theory, concepts, nonfiction.',
      `Without hard work, you'll develop neither judgment nor leverage.`,
      'Any belief you took in a package (ex. Democrat, Catholic, American) is suspect and should be re-evaluated from base principles. ',
      'Read what you love until you love to read.',
      'Reading a book isn’t a race—the better the book, the more slowly it should be absorbed. ',
      'Pointing out obvious exceptions implies either the target isn’t smart or you aren’t. ',
      'The number of books completed is a vanity metric. As you know more, you leave more books unfinished. Focus on new concepts with predictive power. ',
      'To think clearly, understand the basics. If you’re memorizing advanced concepts without being able to re-derive them as needed, you’re lost. ',
      'A calm mind, a fit body, and a house full of love. These things cannot be bought. They must be earned.',
      'There are no external forces affecting your emotions—as much as it may feel that way. ',
      'A rational person can find peace by cultivating indifference to things outside of their control. ',
      'Happiness, love, and passion…aren’t things you find—they’re choices you make.',
      'If there’s something you want to do later, do it now. There is no "later."',
      'The real truths are heresies. They cannot be spoken. Only discovered, whispered, and perhaps read',
      'Before you can lie to another, you must first lie to yourself. ',
      'Whether in commerce, science, or politics—history remembers the artists.',
      'Apply specific knowledge with leverage and eventually, you will get what you deserve. ',
      'When working, surround yourself with people more successful than you. When playing, surround yourself with people happier than you.',
      'Making money is not a thing you do—it’s a skill you learn.',
      'No one can compete with you on being you. Most of life is a search for who and what needs you the most.',
      'Society, business, & money are downstream of technology, which is itself downstream of science. Science applied is the engine of humanity. ',
      `Intentions don't matter. Actions do. That’s why being ethical is hard.`,
      'Embrace accountability and take business risks under your own name. Society will reward you with responsibility, equity, and leverage. ',
      `If you don't own a piece of a business, you don't have a path towards financial freedom.`,
      `If it entertains you now but will bore you someday, it's a distraction. Keep looking.`,
      'If they can train you to do it, then eventually they will train a computer to do it. ',
      'Forget rich versus poor, white-collar versus blue. It’s now leveraged versus un-leveraged. ',
      `You're never going to get rich renting out your time.`,
      'Forty hour work weeks are a relic of the Industrial Age. Knowledge workers function like athletes—train and sprint, then rest and reassess. ',
      'If you want to be part of a great tech company, then you need to be able to SELL or BUILD. If you don’t do either, learn. ',
      'Earn with your mind, not your time.',
      'We waste our time with short-term thinking and busywork. Warren Buffett spends a year deciding and a day acting. That act lasts decades. ',
      'Value your time at an hourly rate, and ruthlessly spend to save time at that rate. You will never be worth more than you think you’re worth. ',
      'Ways to get lucky: • Hope luck finds you. • Hustle until you stumble into it. • Prepare the mind and be sensitive to chances others miss. • Become the best at what you do. Refine what you do until this is true. Opportunity will seek you out. Luck becomes your destiny. ',
      'Reading science, math, and philosophy one hour per day will likely put you at the upper echelon of human success within seven years.',
    ]
  },
  {
    title: 'Marcus Aurelius',
    quotes: [
      'You have power over your mind - not outside events. Realize this, and you will find strength.',
      'Dwell on the beauty of life. Watch the stars, and see yourself running with them.',
      'The happiness of your life depends upon the quality of your thoughts.',
      'Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.',
      'Waste no more time arguing about what a good man should be. Be one.',
      'If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.',
      'When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love ...',
      'The best revenge is to be unlike him who performed the injury.',
      'Accept the things to which fate binds you, and love the people with whom fate brings you together,but do so with all your heart.',
      'The soul becomes dyed with the colour of its thoughts.',
      'It is not death that a man should fear, but he should fear never beginning to live.',
      'Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.',
      'Our life is what our thoughts make it.',
      'If someone is able to show me that what I think or do is not right, I will happily change, for I seek the truth, by which no one was ever truly harmed. It is the person who continues in his self-deception and ignorance who is harmed.',
      'I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others.',
      'Whenever you are about to find fault with someone, ask yourself the following question: What fault of mine most nearly resembles the one I am about to criticize?',
      'If it is not right do not do it; if it is not true do not say it.',
      'The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.',
      'Very little is needed to make a happy life; it is all within yourself in your way of thinking.',
      'The best revenge is not to be like your enemy.',
      'The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.',
      'How much more grievous are the consequences of anger than the causes of it.',
      `Live a good life. If there are gods and they are just, then they will not care how devout you have been, 
but will welcome you based on the virtues you have lived by. 
If there are gods, but unjust, then you should not want to worship them.
If there are no gods, then you will be gone, but will have lived a noble life that will live on in the memories of your loved ones.`,
      'How much time he gains who does not look to see what his neighbour says or does or thinks, but only at what he does himself, to make it just and holy.'
      `Treat what you don't have as non-existent. Look at what you have, the things you value most, and think of how much you'd crave them if you didn't have them. But be careful. Don't feel such satisfaction that you start to overvalue them—that it would upset you to lose them.`,
    ],
  },
];
