window.reminders = [
  'Be more frugal',
  `Don't try to save everyone`,
  'Treasure wife, show her love and appreciation',
  'Treasure siblings, spend time with them',
  'Take good care of your mental health',
  'Be less materialistic',
  'Be grateful',
  'Do less, do it better',
  'Pursue meaningful, valuable work',
  'Be confident - not overconfident',
  'Be kind, Be humble, Be truthful',
  `Don't talk shit about anyone`,
  'Do the hard things first',
  'How you do anything is how you do everything',
  `Don't be judgemental`,
]
